/* Generated By:JavaCC: Do not edit this line. ReaderConstants.java */
package grammaire;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ReaderConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SL_COMMENT = 37;
  /** RegularExpression Id. */
  int ML_COMMENT = 38;
  /** RegularExpression Id. */
  int DOT = 40;
  /** RegularExpression Id. */
  int LPAR = 41;
  /** RegularExpression Id. */
  int RPAR = 42;
  /** RegularExpression Id. */
  int NIL = 43;
  /** RegularExpression Id. */
  int QUOTE = 44;
  /** RegularExpression Id. */
  int CAR = 45;
  /** RegularExpression Id. */
  int CDR = 46;
  /** RegularExpression Id. */
  int COND = 47;
  /** RegularExpression Id. */
  int ATOM = 48;
  /** RegularExpression Id. */
  int EQ = 49;
  /** RegularExpression Id. */
  int SET = 50;
  /** RegularExpression Id. */
  int CONS = 51;
  /** RegularExpression Id. */
  int IMPLODE = 52;
  /** RegularExpression Id. */
  int EXPLODE = 53;
  /** RegularExpression Id. */
  int EVAL = 54;
  /** RegularExpression Id. */
  int APPLY = 55;
  /** RegularExpression Id. */
  int QUIT = 56;
  /** RegularExpression Id. */
  int SYMBOL = 57;
  /** RegularExpression Id. */
  int DIGIT = 58;
  /** RegularExpression Id. */
  int LETTER = 59;
  /** RegularExpression Id. */
  int SPECIAL = 60;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SL_COMMENT = 1;
  /** Lexical state. */
  int IN_ML_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\"",
    "\"\\u0001\"",
    "\"\\u0002\"",
    "\"\\u0003\"",
    "\"\\u0004\"",
    "\"\\u0005\"",
    "\"\\u0006\"",
    "\"\\u0007\"",
    "\"\\b\"",
    "\"\\u000b\"",
    "\"\\f\"",
    "\"\\u000e\"",
    "\"\\u000f\"",
    "\"\\u0010\"",
    "\"\\u0011\"",
    "\"\\u0012\"",
    "\"\\u0013\"",
    "\"\\u0014\"",
    "\"\\u0015\"",
    "\"\\u0016\"",
    "\"\\u0017\"",
    "\"\\u0018\"",
    "\"\\u0019\"",
    "\"\\u001a\"",
    "\"\\u001b\"",
    "\"\\u001c\"",
    "\"\\u001d\"",
    "\"\\u001e\"",
    "\"\\u001f\"",
    "\"\\u007f\"",
    "\"//\"",
    "\"/*\"",
    "<SL_COMMENT>",
    "\"*/\"",
    "<token of kind 39>",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"()\"",
    "\"\\\'\"",
    "\"car\"",
    "\"cdr\"",
    "\"cond\"",
    "\"atom\"",
    "\"eq\"",
    "\"set\"",
    "\"cons\"",
    "\"implode\"",
    "\"explode\"",
    "\"eval\"",
    "\"apply\"",
    "\"quit\"",
    "<SYMBOL>",
    "<DIGIT>",
    "<LETTER>",
    "<SPECIAL>",
  };

}
